### ISSUE TITLE
Can't break the builder, then add Text() in loop, then finish

### ISSUE THREAD

**Issue by yubinchen18** [neodynamic/js-escpos-builder#1]
var escposCommands = doc
                .font(escpos.FontFamily.B)
                .size(0, 0);

            for (var i = 0, len = lines.length; i < len; i++) {
                var line = lines[i];
                escposCommands.text(line);
            }

            escposCommands
                .feed(5)
                .cut()
                .generateUInt8Array();

cpj.binaryPrinterCommands = escposCommands;

            //Send print job to printer!
            cpj.sendToClient();

this doesn't work?

**Comment by neodynamic** [comment]
The code logic should be this one instead
```js
var escpos = Neodynamic.JSESCPOSBuilder;
var doc = new escpos.Document();
doc.font(escpos.FontFamily.B).size(0, 0);
for (var i = 0, len = lines.length; i < len; i++) {
    var line = lines[i];
    doc.text(line);
}
var escposCommands = doc.feed(5).cut().generateUInt8Array();
cpj.binaryPrinterCommands = escposCommands;
//Send print job to printer!
cpj.sendToClient();
```
