### ISSUE TITLE
Cannot print image

### ISSUE THREAD

**Issue by FractalMind** [neodynamic/js-escpos-builder#5]
I try to print my own images:
![logo](https://user-images.githubusercontent.com/5481933/115799859-58d2ad80-a3a7-11eb-8950-34fce2f84682.png)

With the demo image, it works well. But for some reason, only a black square comes out with my custom image
![20210422_201130](https://user-images.githubusercontent.com/5481933/115799825-46f10a80-a3a7-11eb-806a-e8ad9258ec3a.jpg)
The images are almost identical
![2021-04-22_20-10](https://user-images.githubusercontent.com/5481933/115799843-4f494580-a3a7-11eb-88c7-4c9dd5127433.png)

**Why the demo image works and not mine? They are both in base64... What am I missing?**

**Comment by neodynamic** [comment]
It seems your image background is not white
